play_channel_11:
  name: Play Channel 11
  description: Choose media player and start Channel 11
  target:
    entity:
      domain: media_player
play_channel_12:
  name: Play Channel 12
  description: Choose media player and start Channel 12
  target:
    entity:
      domain: media_player

play_channel_13:
  name: Play Channel 13
  description: Choose media player and start Channel 13
  target:
    entity:
      domain: media_player
play_channel_14:
  name: Play Channel 14
  description: Choose media player and start Channel 14
  target:
    entity:
      domain: media_player

get_channel_url:
  name: get_channel_url
  description: get_channel_url
  fields:
    channel_name:
      name: "channel name"
      description: "the name of the channel (for custome channels use the the sensor_name)"
      example: "channel_11"
play_custom_channel:
  name: Play Custome Channel
  description: Choose media player and URL and play it
  target:
    entity:
      domain: media_player
  fields:
    url:
      name: "URL"
      description: use URL or channel name
      required: false
      example: "https://kan11.media.kan.org.il/hls/live/2024514/2024514/master.m3u8"
    channel_name:

      required: false
      example: "kan_kids"
      name: "channel name"
      description: "use URL or channel name"
